/**
 * The test quality report as a document a team can commit.
 *
 * `report.json` is what the UI reads and what a machine should read. It is not what a
 * person reviews in a pull request, and the brief's submission asks for a deliverable an
 * engineering team could actually adopt — so the same report is also written as Markdown,
 * beside the suite it describes, inside the directory a team would copy into their repo.
 *
 * Everything here is a projection of `TestQualityReport`. Nothing is computed that the
 * report does not already carry, and nothing is phrased more confidently than the field
 * it came from: a run with no classifier verdicts says so rather than implying the red
 * tests were understood, and a requirement with a `planned-only` status is printed as
 * "no evidence" rather than as a tick.
 *
 * Pure and dependency-free, so `report-markdown.test.mts` can load it directly.
 */

import type { PrdRequirement, TestQualityReport } from "@/lib/types";

const STATUS_MARK: Record<string, string> = {
  passed: "PASS",
  healed: "HEALED",
  failed: "FAIL",
  quarantined: "QUARANTINED",
  running: "RUNNING",
  pending: "PENDING",
};

const PRD_MARK: Record<NonNullable<PrdRequirement["status"]>, string> = {
  proven: "✅ proven",
  exercised: "⚠️ exercised (test is red)",
  "planned-only": "◻️ planned, never ran",
  uncovered: "❌ no test",
};

export function reportMarkdown(report: TestQualityReport): string {
  const executed = report.passed + report.healed + report.failed;
  const out: string[] = [];
  const push = (...lines: string[]) => out.push(...lines, "");

  push(
    `# Test quality report — ${report.url}`,
    "",
    `Generated by The Odyssey · run \`${report.runId}\` · ${report.finishedAt}`,
    `${fmtDuration(report.durationMs)} · ${fmtUsd(report.costUsd)} · no human between any two stages.`,
  );

  push(
    "## Summary",
    "",
    "| | |",
    "|---|---|",
    `| Plan coverage score | ${report.coverageScore}/100 after ${plural(report.replans, "re-plan")} |`,
    `| Scenarios planned | ${report.scenariosPlanned} |`,
    `| Tests generated | ${report.scenariosGenerated} |`,
    `| Scenarios quarantined | ${report.scenariosQuarantined} — a selector could not be proven on the live page |`,
    `| Passed / healed / failed | ${report.passed} / ${report.healed} / ${report.failed} |`,
    `| Heal attempts | ${report.healAttempts} |`,
    `| Application defects filed | ${report.bugs.length} |`,
    `| Untested surfaces ranked | ${report.risks.length} |`,
  );

  if (executed === 0) {
    push(
      "> **This run executed no tests.** The sections below are real, but none of them is",
      "> evidence about the application. A report that reads as a pass when nothing ran is",
      "> the most misleading thing this document could be, so it says so here first.",
    );
  }

  // --- defects -------------------------------------------------------------
  push("## Application defects", "");
  if (report.bugs.length === 0) {
    push(
      report.triage.length
        ? "_No failure was classified as a genuine application defect._"
        : "_No failure reached the defect classifier in this run._",
    );
  } else {
    push(
      "These failures were classified as the application's fault, not the test's. **The Healer was",
      "withheld and the tests are left red on purpose** — repairing them would delete the signal the",
      "suite exists to produce.",
      "",
    );
    for (const bug of report.bugs) {
      push(
        `### ${bug.title}`,
        "",
        `\`${bug.testId}\` · severity **${bug.severity}**`,
        "",
        ...bug.evidence.map((e) => `- **${e.kind}** — ${e.summary}${e.detail ? ` (${e.detail})` : ""}`),
      );
    }
  }

  // --- scenarios -----------------------------------------------------------
  push(
    "## Scenarios covered",
    "",
    "| Scenario | Flow | Kind | Source | Outcome | Classification |",
    "|---|---|---|---|---|---|",
    ...report.scenarios.map((s) => {
      const result = findResult(report, s.id);
      const triage = report.triage.find((t) => matches(t.testId, s.id));
      return `| ${esc(s.title)} | ${esc(s.flow)} | ${s.kind} | ${s.addedByCritique ? "critic" : "planner"} | ${STATUS_MARK[result?.status ?? "pending"] ?? "—"} | ${triage ? `${triage.verdict} (${triage.confidence.toFixed(2)})` : "—"} |`;
    }),
  );

  // --- healer --------------------------------------------------------------
  push("## Healer actions", "");
  if (report.heals.length === 0) {
    push("_No patch was proposed in this run._");
  } else {
    push(
      "The Healer may rewrite locators and waits. It may not change what a test proves: every patch is",
      "diffed for assertion integrity, and one that deletes, loosens, retargets or negates an assertion",
      "is rejected and the test escalates.",
      "",
    );
    for (const h of report.heals) {
      push(
        `### ${h.testId} — attempt ${h.attempt} — **${h.outcome}**`,
        "",
        h.assertionsIntact ? "Assertions intact." : "**Rejected by the assertion-integrity guard.**",
        "",
        h.summary,
        "",
        "```diff",
        ...h.before.split("\n").map((l) => `- ${l}`),
        ...h.after.split("\n").map((l) => `+ ${l}`),
        "```",
      );
    }
  }

  // --- gaps ----------------------------------------------------------------
  push("## Coverage gaps remaining", "");
  if (report.remainingGaps.length === 0) {
    push("_The plan closed every gap the critic named._");
  } else {
    push(
      "Named by the Coverage Critic and accepted rather than closed — the re-plan allowance ran out, not",
      "the analysis.",
      "",
      ...report.remainingGaps.map((g) => `- **${g.severity}** · ${esc(g.title)} — ${esc(g.rationale)}`),
    );
  }

  // --- risk ----------------------------------------------------------------
  push("## Untested flow risk", "");
  if (report.risks.length === 0) {
    push("_Every surface the crawl found was exercised by a test that ran._");
  } else {
    push(
      "Surfaces this run found and produced no evidence about, scored on what they cost you if they are",
      "broken. `planned` means the test plan covers it and no test ever ran — intent without evidence,",
      "which is worse than not having thought of it.",
      "",
      "| Surface | Risk | Score | State | Why |",
      "|---|---|---|---|---|",
      ...report.risks.map(
        (r) =>
          `| ${esc(r.surface)} | **${r.risk}** | ${r.score}${r.priorScore !== undefined ? ` (computed ${r.priorScore})` : ""} | ${r.status ?? "untested"} | ${r.reasons.map(esc).join("; ")} |`,
      ),
    );
  }

  // --- PRD -----------------------------------------------------------------
  if (report.prd?.length) {
    const without = report.prd.filter((r) => !r.covered);
    push(
      "## PRD traceability",
      "",
      `${report.prd.length - without.length} of ${report.prd.length} stated requirements have a test that ran behind them.`,
      "A requirement mapped to a scenario that never became a running test is reported as having **no",
      "evidence**, not as covered — that distinction is the entire value of this table.",
      "",
      "| Requirement | Status | Covered by |",
      "|---|---|---|",
      ...report.prd.map(
        (r) =>
          `| **${esc(r.id)}** ${esc(r.text)} | ${PRD_MARK[r.status ?? (r.covered ? "proven" : "uncovered")]} | ${r.coveredBy.length ? r.coveredBy.map((c) => `\`${c}\``).join(", ") : "—"} |`,
      ),
    );
    if (report.prdUntraced?.length) {
      push(
        `**${report.prdUntraced.length} scenario(s) trace to no requirement**: ${report.prdUntraced.map((s) => `\`${s}\``).join(", ")}.`,
        "Either the PRD does not ask for this behaviour, or it does and the document does not say so.",
      );
    }
  }

  // --- surfaces ------------------------------------------------------------
  if (report.surfaces?.length) {
    const exercised = report.surfaces.filter((s) => s.status === "exercised");
    push(
      "## Coverage working",
      "",
      `${exercised.length} of ${report.surfaces.length} discovered surfaces were exercised. This is the arithmetic`,
      "behind the two sections above — attribution comes from the emitted test source, not from the plan's",
      "word for it.",
      "",
      "| Surface | State | Attributed by | Basis |",
      "|---|---|---|---|",
      ...report.surfaces.map(
        (s) => `| ${esc(s.surface)} | ${s.status} | ${s.signal} | ${esc(s.basis ?? "—")} |`,
      ),
    );
  }

  push(
    "---",
    "",
    "Every judgment above was made by the orchestrator with no human between stages. The full decision",
    "log, the traces, the videos and the patches are in this run's workspace alongside this file.",
  );

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

// ---------------------------------------------------------------------------

/** Mirrors `lib/report-join.ts`; duplicated only as a predicate to stay dependency-free. */
const matches = (testId: string, scenarioId: string) =>
  testId === scenarioId || testId === `t-${scenarioId}` || testId === `q-${scenarioId}`;

function findResult(report: TestQualityReport, scenarioId: string) {
  let found;
  for (const r of report.results) if (matches(r.testId, scenarioId)) found = r;
  return found;
}

/** A pipe in a cell ends the cell. Newlines end the row. */
const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ").trim();

function fmtDuration(ms: number): string {
  const s = Math.round(ms / 1000);
  return s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${String(s % 60).padStart(2, "0")}s`;
}

const fmtUsd = (n: number) => `$${n.toFixed(n < 1 ? 3 : 2)}`;

const plural = (n: number, word: string) => `${n} ${word}${n === 1 ? "" : "s"}`;
