/**
 * Scaffolds the per-run workspace.
 *
 * The layout follows Playwright's own file contract (`specs/*.md` → `tests/**.spec.ts`,
 * a `seed.spec.ts` for auth bootstrap) so what we emit is a directory a team could
 * copy into their repo and run with a bare `npx playwright test`.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { WATCH_SETTLE_MS, headed } from "./browser-mode";
import { redact } from "./event-log";
import { runDir, runPath } from "./paths";
import type { RunInput } from "@/lib/types";

const SUBDIRS = ["specs", "tests", "results", "results/traces", "results/screenshots", "heal"];

export async function scaffoldWorkspace(runId: string, input: RunInput) {
  await mkdir(runDir(runId), { recursive: true });
  await Promise.all(
    SUBDIRS.map((d) => mkdir(runPath(runId, d), { recursive: true })),
  );

  // Credentials are kept out of the workspace entirely; Phase 3 passes them through
  // the process environment instead, so nothing on disk can leak them.
  const safeInput = redact(
    { ...input, credentials: input.credentials ? { username: input.credentials.username, password: "«redacted»" } : undefined },
    input.credentials ? [input.credentials.password] : [],
  );

  await writeFile(
    runPath(runId, "input.json"),
    JSON.stringify(safeInput, null, 2),
    "utf8",
  );
  await writeFile(runPath(runId, "playwright.config.ts"), playwrightConfig(input), "utf8");
}

function playwrightConfig(input: RunInput): string {
  const watched = headed();
  return `import { defineConfig, devices } from "@playwright/test";

/** Generated by The Odyssey. Committed with the suite it runs. */
export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  // Headed execution is watched by a person, so the suite runs one flow at a time:
  // ${input.options.parallelWorkers} simultaneous windows is faster and unwatchable, and being able to see
  // the suite run is the point. ODYSSEY_HEADLESS=1 restores full parallelism.
  workers: ${watched ? 1 : input.options.parallelWorkers},
  reporter: [["json", { outputFile: "results/results.json" }], ["html", { open: "never" }]],
  use: {
    baseURL: ${JSON.stringify(input.url)},
    headless: ${!watched},${watched ? `\n    launchOptions: { slowMo: ${WATCH_SETTLE_MS / 4} },` : ""}
    trace: "retain-on-failure",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
});
`;
}

/** Writes a run artifact and returns the workspace-relative path for the event. */
export async function writeArtifact(
  runId: string,
  relPath: string,
  contents: string,
): Promise<string> {
  const full = runPath(runId, relPath);
  await mkdir(full.slice(0, full.lastIndexOf("/")), { recursive: true });
  await writeFile(full, contents, "utf8");
  return relPath;
}
