/**
 * Scaffolds the per-run workspace.
 *
 * The layout follows Playwright's own file contract (`specs/*.md` → `tests/**.spec.ts`,
 * a `seed.spec.ts` for auth bootstrap) so what we emit is a directory a team could
 * copy into their repo and run with a bare `npx playwright test`.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { WATCH_SETTLE_MS, WATCH_VIEWPORT, headed } from "./browser-mode";
import { redact } from "./event-log";
import { runDir, runPath } from "./paths";
import type { RunInput } from "@/lib/types";

const SUBDIRS = ["specs", "tests", "results", "results/traces", "results/screenshots", "heal"];

export async function scaffoldWorkspace(runId: string, input: RunInput) {
  await mkdir(runDir(runId), { recursive: true });
  await Promise.all(
    SUBDIRS.map((d) => mkdir(runPath(runId, d), { recursive: true })),
  );

  // Credentials are kept out of the workspace entirely; Phase 3 passes them through
  // the process environment instead, so nothing on disk can leak them.
  const safeInput = redact(
    { ...input, credentials: input.credentials ? { username: input.credentials.username, password: "«redacted»" } : undefined },
    input.credentials ? [input.credentials.password] : [],
  );

  await writeFile(
    runPath(runId, "input.json"),
    JSON.stringify(safeInput, null, 2),
    "utf8",
  );
  // Playwright looks up a tsconfig per imported file, walking upward. Without one here
  // it finds the Odyssey app's own — Next.js settings, `@/*` path aliases and all —
  // and transpiles the generated suite under rules written for a React application.
  // This stops the search at the workspace boundary, and it is also what a team copying
  // this directory into their repo would need.
  await writeFile(runPath(runId, "tsconfig.json"), TSCONFIG, "utf8");

  await writePlaywrightConfig(runId, input);
}

// `types: ["node"]` because a signed-out test reads `process.env.ODYSSEY_PASSWORD` —
// the runner supplies the credential rather than the file carrying it (see
// `agents/credentials.ts`). Playwright transpiles without typechecking, so this changes
// nothing about whether the suite runs; it is here so the suite a team copies into their
// own repo typechecks there.
const TSCONFIG = `${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "CommonJS",
      moduleResolution: "node",
      lib: ["ES2022", "DOM"],
      types: ["node"],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
    },
    include: ["tests/**/*.ts", "playwright.config.ts"],
  },
  null,
  2,
)}\n`;

/**
 * Writes the suite's config. Called once at scaffold time and again by the Generator,
 * which is the point at which the run knows whether it has a session to hand the suite
 * (see `storage-state.ts`) — a config that named `results/state.json` before the file
 * existed would fail every run that never authenticated.
 */
export async function writePlaywrightConfig(
  runId: string,
  input: RunInput,
  opts: { storageState?: string } = {},
) {
  await writeFile(
    runPath(runId, "playwright.config.ts"),
    playwrightConfig(input, opts),
    "utf8",
  );
}

function playwrightConfig(input: RunInput, opts: { storageState?: string }): string {
  const watched = headed();
  return `import { defineConfig, devices } from "@playwright/test";

/** Generated by The Odyssey. Committed with the suite it runs. */
export default defineConfig({
  testDir: "./tests",
  // Every artifact of a run stays inside that run's workspace, so the report can cite
  // a trace or a video by a path relative to the directory it ships in.
  outputDir: "./results/artifacts",
  fullyParallel: true,
  // Headed execution is watched by a person, so the suite runs one flow at a time:
  // ${input.options.parallelWorkers} simultaneous windows is faster and unwatchable, and being able to see
  // the suite run is the point. ODYSSEY_HEADLESS=1 restores full parallelism.
  workers: ${watched ? 1 : input.options.parallelWorkers},${
    watched
      ? `
  // Every action pauses so a person can follow it, which is worth roughly a second a
  // step — Playwright's 30s default would time out flows that are merely being watched.
  timeout: 90_000,`
      : ""
  }
  // Both reporters are given an explicit path inside the workspace. The JSON one has to
  // be — the executor reads it back — but the HTML one matters just as much: left to its
  // default it writes a \`playwright-report/\` beside the *project's* package.json rather
  // than beside this config, so every run scribbled over the previous run's report in the
  // repo root, and the promise three lines above this was false.
  reporter: [
    ["json", { outputFile: "results/results.json" }],
    ["html", { open: "never", outputFolder: "results/report" }],
  ],
  use: {
    baseURL: ${JSON.stringify(input.url)},
    headless: ${!watched},${watched ? `\n    launchOptions: { slowMo: ${WATCH_SETTLE_MS / 4} },` : ""}${
      opts.storageState
        ? `
    // The signed-in session, dumped out of the browser Recon logged in with. Cookies
    // *and* localStorage: this target keeps its token in the latter and none in the
    // former, so a cookie-only hand-off runs the whole suite logged out.
    storageState: ${JSON.stringify(opts.storageState)},`
        : ""
    }
    trace: "retain-on-failure",
    video: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      name: "chromium",
      // The project's \`use\` is merged *over* the top-level one, so anything that has to
      // survive has to be stated here — including the viewport, which
      // \`devices["Desktop Chrome"]\` pins to 1280x720.
      use: {
        ...devices["Desktop Chrome"],${
          watched
            ? `
        // A locator is proven at whatever size the Generator browsed at, and a
        // responsive app is a different app at a different width: a nav that is a row of
        // buttons at 1280 is a hamburger at 900, so a locator resolved in one is missing
        // or covered in the other. Proving at one viewport and asserting at another is
        // not a test of the app, it is a test of the coincidence that they agree.
        viewport: { width: ${WATCH_VIEWPORT.width}, height: ${WATCH_VIEWPORT.height} },`
            : ""
        }
      },
    },
  ],
});
`;
}

/** Writes a run artifact and returns the workspace-relative path for the event. */
export async function writeArtifact(
  runId: string,
  relPath: string,
  contents: string,
): Promise<string> {
  const full = runPath(runId, relPath);
  await mkdir(full.slice(0, full.lastIndexOf("/")), { recursive: true });
  await writeFile(full, contents, "utf8");
  return relPath;
}
